name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@master
        with:
          node-version: '16.x'
      - run: node scripts/generate-env.js "${{ secrets.ENVIRONMENT_FILE }}"
      - run: npm install
      - run: npm run build:prod
      - uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
